-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 18:47:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotelmanagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelmanagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelmanagement` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotelmanagement` ;

-- -----------------------------------------------------
-- Table `hotelmanagement`.`customer_management`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`customer_management` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`customer_management` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(50) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `email_address` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_address` (`email_address` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelmanagement`.`Hotel_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`Hotel_service` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`Hotel_service` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `opening_hours` VARCHAR(50) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelmanagement`.`customer_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`customer_service` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`customer_service` (
  `customer_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `booking_date` DATE NOT NULL,
  PRIMARY KEY (`customer_id`, `service_id`, `booking_date`),
  INDEX `service_id` (`service_id` ASC) VISIBLE,
  CONSTRAINT `customer_service_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hotelmanagement`.`customer_management` (`customer_id`),
  CONSTRAINT `customer_service_ibfk_2`
    FOREIGN KEY (`service_id`)
    REFERENCES `hotelmanagement`.`Hotel_service` (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelmanagement`.`Room_management`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`Room_management` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`Room_management` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `status` ENUM('available', 'occupied', 'cleaning') NULL DEFAULT 'available',
  `price_per_night` DECIMAL(10,2) NULL DEFAULT NULL,
  `special_amenities` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelmanagement`.`Room_reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`Room_reservation` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`Room_reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `arrival_date` DATE NULL DEFAULT NULL,
  `departure_date` DATE NULL DEFAULT NULL,
  `num_guests` INT NULL DEFAULT NULL,
  `special_preferences` VARCHAR(255) NULL DEFAULT NULL,
  `reservation_status` ENUM('confirmed', 'canceled', 'pending') NULL DEFAULT 'pending',
  PRIMARY KEY (`reservation_id`),
  INDEX `room_id` (`room_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `reservation_ibfk_1`
    FOREIGN KEY (`room_id`)
    REFERENCES `hotelmanagement`.`Room_management` (`room_id`),
  CONSTRAINT `reservation_ibfk_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hotelmanagement`.`customer_management` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelmanagement`.`Customer_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`Customer_feedback` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`Customer_feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_id` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `feedback_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `reservation_id` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `feedback_ibfk_1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `hotelmanagement`.`Room_reservation` (`reservation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelmanagement`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelmanagement`.`invoice` ;

CREATE TABLE IF NOT EXISTS `hotelmanagement`.`invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_id` INT NULL DEFAULT NULL,
  `room_charge` DECIMAL(10,2) NULL DEFAULT NULL,
  `service_charge` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `tax` DECIMAL(10,2) NULL DEFAULT NULL,
  `payment_status` ENUM('paid', 'due', 'partially paid') NULL DEFAULT 'due',
  PRIMARY KEY (`invoice_id`),
  INDEX `reservation_id` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `invoice_ibfk_1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `hotelmanagement`.`Room_reservation` (`reservation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
